<script lang="ts">
	export let data;

	$: normalized = (data.staged.normalized ?? {}) as Record<string, unknown>;
	$: raw = (data.staged.raw ?? {}) as Record<string, unknown>;

	function asString(v: unknown): string {
		return typeof v === 'string' ? v : '';
	}

	/**
	 * Extract image URLs from a WC product's raw payload. WC stores them
	 * under `images` as an array of `{ id, src, name, alt, ... }`.
	 */
	function productImageUrls(rawObj: Record<string, unknown>): Array<{ src: string; alt: string }> {
		const list = (rawObj.images as Array<{ src?: string; alt?: string; name?: string }>) ?? [];
		return list
			.filter((i) => typeof i.src === 'string' && i.src)
			.map((i) => ({ src: i.src as string, alt: i.alt || i.name || '' }));
	}

	function priceLabel(n: Record<string, unknown>): string {
		const sale = typeof n.salePrice === 'string' && n.salePrice ? n.salePrice : null;
		const reg = typeof n.regularPrice === 'string' && n.regularPrice ? n.regularPrice : null;
		const fallback = typeof n.price === 'string' ? n.price : '';
		const currency = typeof n.currency === 'string' && n.currency ? n.currency : '';
		const main = sale && reg && sale !== reg ? `${sale} (was ${reg})` : reg || fallback || '0';
		return currency ? `${main} ${currency}` : main;
	}
</script>

<svelte:head>
	<title>
		Migration preview — {data.staged.type}
		{data.staged.sourceId}
	</title>
	<!-- Scoped WordPress block CSS, generated by
	     scripts/build-wp-imported-css.mjs. Loaded only on this admin preview
	     route so the rest of be-BOP is unaffected. -->
	<link rel="stylesheet" href="/css/wp-imported.css" />
</svelte:head>

<main class="mx-auto max-w-4xl py-8 px-6">
	<div class="text-sm text-gray-500 mb-4 border-b pb-2">
		<strong>Migration preview</strong> — type
		<span class="font-mono">{data.staged.type}</span> •
		<span class="font-mono">{data.staged.sourceId}</span>
		(this is a draft preview — not promoted yet)
	</div>

	{#if data.staged.type === 'cmsPage'}
		<article>
			<h1 class="text-4xl mb-2">{asString(normalized.title) || '(untitled)'}</h1>
			{#if normalized.slug}
				<p class="text-sm text-gray-500 mb-4">slug: {normalized.slug}</p>
			{/if}
			{#if normalized.excerpt}
				<p class="text-lg italic mb-6">
					<!-- eslint-disable-next-line svelte/no-at-html-tags -->
					{@html asString(normalized.excerpt)}
				</p>
			{/if}
			<div class="wp-imported">
				<!-- eslint-disable-next-line svelte/no-at-html-tags -->
				{@html asString(normalized.content)}
			</div>
		</article>
	{:else if data.staged.type === 'product'}
		{@const imgs = productImageUrls(raw)}
		<article class="grid lg:grid-cols-[40%_1fr] gap-6">
			<div>
				{#if imgs.length > 0}
					<img
						src={imgs[0].src}
						alt={imgs[0].alt}
						class="w-full h-auto rounded border border-gray-200"
					/>
					{#if imgs.length > 1}
						<div class="flex flex-wrap gap-2 mt-2">
							{#each imgs.slice(1) as img}
								<img
									src={img.src}
									alt={img.alt}
									class="w-20 h-20 object-cover rounded border border-gray-200"
								/>
							{/each}
						</div>
					{/if}
				{:else}
					<div
						class="aspect-square bg-gray-100 rounded border border-gray-200 flex items-center
							justify-center text-gray-400 text-sm"
					>
						no image
					</div>
				{/if}
			</div>
			<div class="flex flex-col gap-3">
				<h1 class="text-3xl">{asString(normalized.name) || '(unnamed)'}</h1>
				{#if normalized.slug || normalized.sku}
					<p class="text-sm text-gray-500">
						{#if normalized.slug}slug: {normalized.slug}{/if}
						{#if normalized.slug && normalized.sku} • {/if}
						{#if normalized.sku}SKU: {normalized.sku}{/if}
					</p>
				{/if}
				<p class="text-2xl font-semibold">{priceLabel(normalized)}</p>
				{#if normalized.stockStatus || typeof normalized.stockQuantity === 'number'}
					<p class="text-sm">
						{#if normalized.stockStatus}
							<span class="font-semibold">{normalized.stockStatus}</span>
						{/if}
						{#if typeof normalized.stockQuantity === 'number'}
							<span class="text-gray-500"> ({normalized.stockQuantity} in stock)</span>
						{/if}
					</p>
				{/if}
				{#if normalized.shortDescription}
					<p class="italic text-gray-700">{normalized.shortDescription}</p>
				{/if}
			</div>
		</article>
		{#if normalized.description}
			<section class="mt-8">
				<h2 class="text-xl mb-2">Description</h2>
				<div class="wp-imported">
					<!-- eslint-disable-next-line svelte/no-at-html-tags -->
					{@html asString(normalized.description)}
				</div>
			</section>
		{/if}
		<p class="text-xs text-gray-500 mt-6 italic">
			Images shown above are hot-linked from the WordPress source. They become be-BOP-hosted
			when the product is promoted.
		</p>
	{:else if data.staged.type === 'orphan' || !data.staged.normalized}
		<p class="text-gray-500 italic">
			This object has no normalized payload (orphan or unprocessed). Raw source dump below.
		</p>
		<pre class="text-xs bg-gray-100 p-3 overflow-auto mt-4">{JSON.stringify(
				data.staged.raw,
				null,
				2
			)}</pre>
	{:else}
		<p class="text-gray-500 italic">
			No specialized preview for type
			<span class="font-mono">{data.staged.type}</span> yet — showing normalized fields.
		</p>
		<table class="w-full mt-4">
			<tbody>
				{#each Object.entries(normalized) as [key, value]}
					<tr class="border-b">
						<td class="align-top font-semibold pr-4 py-2 w-48">{key}</td>
						<td class="font-mono whitespace-pre-wrap break-words text-sm py-2">
							{typeof value === 'string' ? value : JSON.stringify(value, null, 2)}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	{/if}
</main>
